---
- hosts: "{{ var_host | default('all') }}"
  become: yes
  become_user: root
  become_method: sudo
  tasks:
  - name: install packages in redhat
    yum: name = "{{ item }}" state = present
    with_items:
     - httpd
     - php
     - gcc
     - glibc
     - glibc-common
     - gd
     - gd-devel
     - make
     - net-snmp
    when: 'ansible_os_family == "Redhat"'
  - name: install packages in ubuntu
    apt: name = "{{ item }}" state = present update_cache = yes
    with_items:
     - httpd
     - php
     - gcc
     - glibc
     - glibc-common
     - gd
     - gd-devel
     - make
     - net-snmp
    when: 'ansible_os_family == "Debian"' 
